package uz.azim.stocks.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "quote_table")
data class Quote(
    @PrimaryKey
    val symbol: String,
    val language: String,
    val region: String,
    val quoteType: String,
    val quoteSourceName: String,
    val triggerable: Boolean,
    val currency: String,
    val sharesOutstanding: Long,
    val fiftyDayAverage: Double,
    val fiftyDayAverageChange: Double,
    val fiftyDayAverageChangePercent: Double,
    val twoHundredDayAverage: Double,
    val twoHundredDayAverageChange: Double,
    val twoHundredDayAverageChangePercent: Double,
    val marketCap: Long,
    val sourceInterval: Int,
    val exchangeDataDelayedBy: Int,
    val exchangeTimezoneName: String,
    val exchangeTimezoneShortName: String,
    val gmtOffSetMilliseconds: Int,
    val esgPopulated: Boolean,
    val tradeable: Boolean,
    val regularMarketChangePercent: Double,
    val firstTradeDateMilliseconds: Long,
    val priceHint: Int,
    val regularMarketChange: Double,
    val regularMarketTime: Int,
    val regularMarketPrice: Double,
    val regularMarketDayHigh: Double,
    val regularMarketDayRange: String,
    val regularMarketDayLow: Double,
    val regularMarketVolume: Int,
    val regularMarketPreviousClose: Double,
    val exchange: String,
    val market: String,
    val messageBoardId: String,
    val fullExchangeName: String,
    val shortName: String,
    val longName: String,
    val financialCurrency: String,
    val regularMarketOpen: Double,
    val averageDailyVolume3Month: Int,
    val averageDailyVolume10Day: Int,
    val fiftyTwoWeekLowChange: Double,
    val fiftyTwoWeekLowChangePercent: Double,
    val fiftyTwoWeekRange: String,
    val fiftyTwoWeekHighChange: Double,
    val fiftyTwoWeekHighChangePercent: Double,
    val fiftyTwoWeekLow: Double,
    val fiftyTwoWeekHigh: Double,
    val marketState: String,
    val displayName: String,
    val epsTrailingTwelveMonths: Double,
    val bookValue: Double,
    val priceToBook: Double,
    val bid: Double,
    val ask: Double,
    val bidSize: Int,
    val askSize: Int,
    val dividendDate: Int,
    val epsCurrentYear: Double,
    val priceEpsCurrentYear: Double,
    val prevName: String?,
    val nameChangeDate: String?,
    val postMarketChangePercent: Double,
    val postMarketTime: Int,
    val postMarketPrice: Double,
    val postMarketChange: Double,
    val epsForward: Double,
    val forwardPE: Double,
    val earningsTimestamp: Int,
    val earningsTimestampStart: Int,
    val earningsTimestampEnd: Int,
    val trailingAnnualDividendRate: Double,
    val trailingAnnualDividendYield: Double,
    val trailingPE: Double,
    val ipoExpectedDate: String?,
    var isFavorite:Boolean = false
)